image:
  pullPolicy: Always
  tag: "latest-develop"

imagePullSecrets:
  - name: github-registry-auth

ingress:
  enabled: true
  hosts:
    - host: management.provider.edc.dev.possible-x.de
      paths:
        - path: /
          portNumber: 80
          pathType: Prefix
  tls:
    - secretName: dev-provider-edc-management-tls
      hosts:
      - management.provider.edc.dev.possible-x.de

service:
  type: NodePort
  port: 80
  targetPort: 8080

application:
  variables:
    - name: provider-management-variables
      data:
        SPRING_PROFILES_ACTIVE: dev 
        FH_CATALOG_URL: https://possible.fokus.fraunhofer.de/api/hub/repo
  secrets:
    - provider-management-secrets