image:
  pullPolicy: Always
  tag: "latest-develop"

imagePullSecrets:
  - name: github-registry-auth

ingress:
  enabled: true
  hosts:
    - host: management.consumer.edc.poc.possible-x.de
      paths:
        - path: /
          portNumber: 80
          pathType: Prefix
  tls:
    - secretName: demo-consumer-edc-management-tls
      hosts:
        - management.consumer.edc.poc.possible-x.de

service:
  type: NodePort
  port: 80
  targetPort: 8080

application:
  variables:
    - name: consumer-management-variables
      data:
        SPRING_PROFILES_ACTIVE: dev
        FH_CATALOG_URL: https://possible.fokus.fraunhofer.de/api/hub/repo
  secrets:
    - consumer-management-secrets